name: Error Notifier

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          # Run your tests or linting command here
          # Replace with actual test command
          python -m unittest || echo "Tests failed" > error.log
          
      - name: Notify Discord on Failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"Error: $(cat error.log)\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
