name: Code Push Notifier

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          # Run your tests or linting command here
          # Replace with your actual test command
          python -m unittest || echo "Tests failed" > error.log

      - name: Notify Discord on Failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"❌ Code push failed: $(cat error.log)\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord on Success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"✅ Code push succeeded and passed all checks!\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
